[project]
name = "local-ide-with-aws-step-functions"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "aws-sam-cli>=1.138.0",
    "boto3>=1.38.17",
]

[dependency-groups]
dev = [
    "pytest>=8.3.5",
]
