name: 'multitenant_analytics'
version: '1.0.0'
config-version: 2

profile: 'multitenant_analytics'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  multitenant_analytics:
    +materialized: view
    +schema: analytics

vars:
  # Zero-ETL configuration
  zeroetl_database: "multitenant_analytics_zeroetl"
  tenant_schemas:
    - "tenant_a"
    - "tenant_b"
    - "tenant_c"
