name: langfuse-nginx  # プロジェクト名を指定して警告を防ぐ

services:
  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    volumes:
      - ./nginx/templates:/etc/nginx/templates
      - ./nginx/setup-nginx.sh:/docker-entrypoint.d/40-setup-nginx.sh
    ports:
      - "8081:80"  # ポート8081でアクセス
    environment:
      - USE_CODE_SERVER=false  # true/falseで切り替え
      - CODE_SERVER_HOST=code-server
      - CODE_SERVER_PORT=8080
    networks:
      - langfuse_network
      - app_network
    restart: unless-stopped
    entrypoint: ["/bin/bash", "/docker-entrypoint.d/40-setup-nginx.sh"]

networks:
  langfuse_network:
    name: langfuse_default
    external: true
  app_network:
    name: 4langfuse_app-network
    external: true
