AWSTemplateFormatVersion: '2010-09-09'
Description: 'Cognito User Pool for CopilotKit AgentCore Authentication (Simple SPA Configuration)'

Metadata:
  'AWS::CloudFormation::Interface':
    ParameterGroups:
      - Label:
          default: 'Project Configuration'
        Parameters:
          - ProjectName
      - Label:
          default: 'Frontend Configuration'
        Parameters:
          - FrontendDomain

Parameters:
  ProjectName:
    Type: String
    Default: 'copilotkit-agentcore'
    Description: 'Project name used for resource naming'
  
  FrontendDomain:
    Type: String
    Default: 'localhost:3000'
    Description: 'Frontend domain for callback URLs (e.g., example.com or localhost:3000)'

Resources:
  # Cognito User Pool
  UserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: !Sub '${ProjectName}-user-pool'
      # Email as username
      UsernameAttributes:
        - email
      # Auto-verify email
      AutoVerifiedAttributes:
        - email
      # User attributes schema
      Schema:
        - Name: email
          Required: true
          Mutable: false
        - Name: name
          Required: false
          Mutable: true
      # Password policy
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireUppercase: true
          RequireLowercase: true
          RequireNumbers: true
          RequireSymbols: true
      # Account recovery
      AccountRecoverySetting:
        RecoveryMechanisms:
          - Name: verified_email
            Priority: 1
      # Admin user creation settings
      AdminCreateUserConfig:
        AllowAdminCreateUserOnly: false
      # MFA configuration (OFF for simplicity)
      MfaConfiguration: 'OFF'
      # Tags
      UserPoolTags:
        Name: !Sub '${ProjectName}-user-pool'
        Project: !Ref ProjectName
        Environment: 'development'

  # User Pool Domain for OAuth endpoints
  UserPoolDomain:
    Type: AWS::Cognito::UserPoolDomain
    Properties:
      Domain: !Sub '${ProjectName}-${AWS::AccountId}'
      UserPoolId: !Ref UserPool

  # User Pool Client (SPA - Public Client)
  UserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: !Sub '${ProjectName}-app-client'
      UserPoolId: !Ref UserPool
      # Public client - no secret for SPA
      GenerateSecret: false
      # OAuth flows for SPA
      AllowedOAuthFlows:
        - code
        - implicit
      AllowedOAuthFlowsUserPoolClient: true
      # OAuth scopes
      AllowedOAuthScopes:
        - openid
        - email
        - profile
      # Callback URLs (localhost + production)
      CallbackURLs:
        - !Sub 'https://${FrontendDomain}/api/auth/callback/cognito'
        - 'http://localhost:3000/api/auth/callback/cognito'
        - 'http://localhost:3000'
      # Logout URLs
      LogoutURLs:
        - !Sub 'https://${FrontendDomain}'
        - 'http://localhost:3000'
      # Identity providers
      SupportedIdentityProviders:
        - COGNITO
      # Token validity
      AccessTokenValidity: 60
      IdTokenValidity: 60
      RefreshTokenValidity: 30
      TokenValidityUnits:
        AccessToken: minutes
        IdToken: minutes
        RefreshToken: days
      # Security settings
      PreventUserExistenceErrors: 'ENABLED'
      EnableTokenRevocation: true
      # PKCE for additional security
      ExplicitAuthFlows:
        - ALLOW_USER_SRP_AUTH
        - ALLOW_REFRESH_TOKEN_AUTH
        - ALLOW_USER_PASSWORD_AUTH

Outputs:
  UserPoolId:
    Description: 'Cognito User Pool ID'
    Value: !Ref UserPool
    Export:
      Name: !Sub '${AWS::StackName}-UserPoolId'

  UserPoolArn:
    Description: 'Cognito User Pool ARN'
    Value: !GetAtt UserPool.Arn
    Export:
      Name: !Sub '${AWS::StackName}-UserPoolArn'

  UserPoolClientId:
    Description: 'Cognito User Pool Client ID'
    Value: !Ref UserPoolClient
    Export:
      Name: !Sub '${AWS::StackName}-UserPoolClientId'

  UserPoolDomain:
    Description: 'Cognito User Pool Domain'
    Value: !Sub '${ProjectName}-${AWS::AccountId}.auth.${AWS::Region}.amazoncognito.com'
    Export:
      Name: !Sub '${AWS::StackName}-UserPoolDomain'

  HostedUIUrl:
    Description: 'Cognito Hosted UI URL'
    Value: !Sub 'https://${ProjectName}-${AWS::AccountId}.auth.${AWS::Region}.amazoncognito.com/login?client_id=${UserPoolClient}&response_type=code&scope=openid+email+profile&redirect_uri=http://localhost:3000/api/auth/callback/cognito'
    Export:
      Name: !Sub '${AWS::StackName}-HostedUIUrl'

  DiscoveryUrl:
    Description: 'OIDC Discovery URL (for AgentCore Runtime)'
    Value: !Sub 'https://cognito-idp.${AWS::Region}.amazonaws.com/${UserPool}/.well-known/openid-configuration'
    Export:
      Name: !Sub '${AWS::StackName}-DiscoveryUrl'

  IssuerUrl:
    Description: 'Cognito Issuer URL (for NextAuth.js)'
    Value: !Sub 'https://cognito-idp.${AWS::Region}.amazonaws.com/${UserPool}'
    Export:
      Name: !Sub '${AWS::StackName}-IssuerUrl'

  TokenEndpoint:
    Description: 'OAuth2 Token Endpoint'
    Value: !Sub 'https://${ProjectName}-${AWS::AccountId}.auth.${AWS::Region}.amazoncognito.com/oauth2/token'
    Export:
      Name: !Sub '${AWS::StackName}-TokenEndpoint'

  AuthorizationEndpoint:
    Description: 'OAuth2 Authorization Endpoint'
    Value: !Sub 'https://${ProjectName}-${AWS::AccountId}.auth.${AWS::Region}.amazoncognito.com/oauth2/authorize'
    Export:
      Name: !Sub '${AWS::StackName}-AuthorizationEndpoint'
