model_list:
  - model_name: bedrock-converse-us-claude-3-7-sonnet-v1
    litellm_params:
      model: bedrock/converse/us.anthropic.claude-3-7-sonnet-20250219-v1:0
      aws_access_key_id: os.environ/AWS_ACCESS_KEY_ID
      aws_secret_access_key: os.environ/AWS_SECRET_ACCESS_KEY
      aws_region_name: os.environ/AWS_REGION_NAME

  - model_name: bedrock-us-claude-3-5-sonnet-v2
    litellm_params:
      model: bedrock/converse/us.anthropic.claude-3-5-sonnet-20241022-v2:0
      aws_access_key_id: os.environ/AWS_ACCESS_KEY_ID
      aws_secret_access_key: os.environ/AWS_SECRET_ACCESS_KEY
      aws_region_name: os.environ/AWS_REGION_NAME
  
  - model_name: bedrock-apac-claude-3-5-sonnet-v2
    litellm_params:
      model: bedrock/converse/apac.anthropic.claude-3-5-sonnet-20241022-v2:0
      aws_access_key_id: os.environ/AWS_ACCESS_KEY_ID
      aws_secret_access_key: os.environ/AWS_SECRET_ACCESS_KEY
      aws_region_name: ap-northeast-1
  
  - model_name: bedrock-claude-3-5-sonnet-v1
    litellm_params:
       model: bedrock/converse/anthropic.claude-3-5-sonnet-20240620-v1:0
       aws_access_key_id: os.environ/AWS_ACCESS_KEY_ID
       aws_secret_access_key: os.environ/AWS_SECRET_ACCESS_KEY
       aws_region_name: os.environ/AWS_REGION_NAME

  - model_name: bedrock-converse-us-deepseek-r1-v1
    litellm_params:
       model: bedrock/converse/us.deepseek.r1-v1:0
       aws_access_key_id: os.environ/AWS_ACCESS_KEY_ID
       aws_secret_access_key: os.environ/AWS_SECRET_ACCESS_KEY
       aws_region_name: os.environ/AWS_REGION_NAME

  - model_name: bedrock-converse-us-nova-pro-v1
    litellm_params:
       model: bedrock/converse/us.amazon.nova-pro-v1:0
       aws_access_key_id: os.environ/AWS_ACCESS_KEY_ID
       aws_secret_access_key: os.environ/AWS_SECRET_ACCESS_KEY
       aws_region_name: os.environ/AWS_REGION_NAME

  - model_name: bedrock-converse-apac-nova-pro-v1
    litellm_params:
       model: bedrock/converse/apac.amazon.nova-pro-v1:0
       aws_access_key_id: os.environ/AWS_ACCESS_KEY_ID
       aws_secret_access_key: os.environ/AWS_SECRET_ACCESS_KEY
       aws_region_name: ap-northeast-1

litellm_settings:
  fallbacks: [
    {"bedrock-converse-us-claude-3-7-sonnet-v1": 
      [
        "bedrock-us-claude-3-5-sonnet-v2",
        "bedrock-apac-claude-3-5-sonnet-v2",
        "bedrock-claude-3-5-sonnet-v1"
      ]
    },
    {"bedrock-converse-us-deepseek-r1-v1":
      [
        "bedrock-converse-us-nova-pro-v1",
        "bedrock-converse-us-nova-pro-v1"
      ]
    }
  ]
  num_retries: 2
  request_timeout: 30
  aws_access_key_id: os.environ/AWS_ACCESS_KEY_ID
  aws_secret_access_key: os.environ/AWS_SECRET_ACCESS_KEY
  aws_region_name: os.environ/AWS_REGION_NAME
  drop_params: true
  success_callback: ["mlflow"]
  failure_callback: ["mlflow"]
  callbacks: ["mlflow"]
  # MLflow の設定（AWS環境用）
  mlflow:
    tracking_uri: os.environ/MLFLOW_TRACKING_URI
    experiment_name: os.environ/MLFLOW_EXPERIMENT_NAME
    # MLflow に記録するメトリクス
    metrics:
      - latency
      - prompt_tokens
      - completion_tokens
      - total_tokens
      - cost_usd  # AWS環境ではコストも記録
    # MLflow に記録するパラメータ
    params:
      - model
      - messages
      - max_tokens
      - region  # AWS リージョン情報
    # MLflow に記録するタグ
    tags:
      - request_id
      - deployment
      - user
      - aws_account_id  # AWS アカウント情報
      - sagemaker_endpoint  # SageMaker エンドポイント情報

general_settings:
  log_level: debug
  openai_api_base: "/v1"
  disable_user_auth: true

router_settings:
  default_model: bedrock-converse-us-claude-3-7-sonnet-v1
  failover: true
  timeout: 30
  retries: 3

openapi:
  openapi_version: "3.1.0"
  title: "LiteLLM API"
  description: "LiteLLM API for multiple LLM models"
  servers: