Resources:
  handlerServiceRole187D5A5A:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
        Version: "2012-10-17"
      ManagedPolicyArns:
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
    Metadata:
      aws:cdk:path: CdkStack/handler/ServiceRole/Resource
  handlerE1533BD5:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket:
          Ref: AssetParameters3cdca015917cbfe299da1c92f577a7b0e9a6cbbbef02c5277f16957f8df1c064S3Bucket08979079
        S3Key:
          Fn::Join:
            - ""
            - - Fn::Select:
                  - 0
                  - Fn::Split:
                      - "||"
                      - Ref: AssetParameters3cdca015917cbfe299da1c92f577a7b0e9a6cbbbef02c5277f16957f8df1c064S3VersionKey8C267BA3
              - Fn::Select:
                  - 1
                  - Fn::Split:
                      - "||"
                      - Ref: AssetParameters3cdca015917cbfe299da1c92f577a7b0e9a6cbbbef02c5277f16957f8df1c064S3VersionKey8C267BA3
      Role:
        Fn::GetAtt:
          - handlerServiceRole187D5A5A
          - Arn
      Handler: bootstrap
      Runtime: provided.al2
    DependsOn:
      - handlerServiceRole187D5A5A
    Metadata:
      aws:cdk:path: CdkStack/handler/Resource
      aws:asset:path: /home/ec2-user/environment/littlemex/aws-samples/cdk/cdk-lang-typescript-lambda-go-sample/cdk/cdk.out/asset.3cdca015917cbfe299da1c92f577a7b0e9a6cbbbef02c5277f16957f8df1c064
      aws:asset:property: Code
  CDKMetadata:
    Type: AWS::CDK::Metadata
    Properties:
      Analytics: v2:deflate64:H4sIAAAAAAAAAzWNzQ6CMBCEn4V7Wah68aaQ6NXgE6xlJeWnTbqtHpq+uxTiaWays99IkPIMdXHBL5eqn6qorCOIT49qEldm8qsdtBlEaw17F5QX7ds80OFCnlwOHbENTlH2a6vXXluTREbGGZdXj+Vg4W5vwah8EhoXiJ2dt4+sSfCxxLzGsI2uGZqgJvINMomdAmv7z0hJGNsTjFx9ZA2HE8hiZK1LF4zXC0G36w/T+Lkk4QAAAA==
    Metadata:
      aws:cdk:path: CdkStack/CDKMetadata/Default
    Condition: CDKMetadataAvailable
Parameters:
  AssetParameters3cdca015917cbfe299da1c92f577a7b0e9a6cbbbef02c5277f16957f8df1c064S3Bucket08979079:
    Type: String
    Description: S3 bucket for asset "3cdca015917cbfe299da1c92f577a7b0e9a6cbbbef02c5277f16957f8df1c064"
  AssetParameters3cdca015917cbfe299da1c92f577a7b0e9a6cbbbef02c5277f16957f8df1c064S3VersionKey8C267BA3:
    Type: String
    Description: S3 key for asset version "3cdca015917cbfe299da1c92f577a7b0e9a6cbbbef02c5277f16957f8df1c064"
  AssetParameters3cdca015917cbfe299da1c92f577a7b0e9a6cbbbef02c5277f16957f8df1c064ArtifactHashC8E1372A:
    Type: String
    Description: Artifact hash for asset "3cdca015917cbfe299da1c92f577a7b0e9a6cbbbef02c5277f16957f8df1c064"
Conditions:
  CDKMetadataAvailable:
    Fn::Or:
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - af-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-northeast-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-northeast-2
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-southeast-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-southeast-2
          - Fn::Equals:
              - Ref: AWS::Region
              - ca-central-1
          - Fn::Equals:
              - Ref: AWS::Region
              - cn-north-1
          - Fn::Equals:
              - Ref: AWS::Region
              - cn-northwest-1
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-central-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-north-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-2
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-3
          - Fn::Equals:
              - Ref: AWS::Region
              - me-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - sa-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-east-2
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - us-west-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-west-2

