#!/bin/bash
set -e

# Color codes for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Function to print colored output
print_info() {
    echo -e "${BLUE}[INFO]${NC} $1"
}

print_success() {
    echo -e "${GREEN}[SUCCESS]${NC} $1"
}

print_warning() {
    echo -e "${YELLOW}[WARNING]${NC} $1"
}

print_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

# Show usage
show_usage() {
    cat << EOF
Usage: $0 CONFIG_FILE [DBT_COMMAND]

Real dbt execution script for Redshift Serverless via Bastion Host
Runs actual dbt models with Zero-ETL integration support

ARGUMENTS:
    CONFIG_FILE     Path to config.json file (required)
    DBT_COMMAND     dbt command to execute (optional, default: "dbt run")

DBT_COMMAND OPTIONS:
    "dbt run"           Run dbt models (default)
    "dbt test"          Run dbt tests  
    "dbt run --models MODEL_NAME"  Run specific model
    "dbt docs generate" Generate documentation
    "dbt seed"          Load seed data

EXAMPLES:
    # Run all dbt models
    $0 config.json "dbt run"

    # Run specific model
    $0 config.json "dbt run --models all_users"

    # Run tests
    $0 config.json "dbt test"

ENVIRONMENT VARIABLES (optional, overrides auto-detection):
    REDSHIFT_HOST       Redshift Serverless endpoint
    REDSHIFT_PORT       Redshift port (default: 5439)
    REDSHIFT_PASSWORD   Redshift admin password
    REDSHIFT_USER       Redshift admin user
    REDSHIFT_DATABASE   Redshift database name (default: dev)

PREREQUISITES:
    1. bastion-redshift-connection.json must exist (generated by configure-bastion-redshift-sg.py)
    2. dbt-redshift must be installed (run --step0 first)
    3. Zero-ETL integration database must be created
    4. Script must be executed from workspace directory with connection file

EOF
}

# Parse arguments
if [[ $# -lt 1 ]] || [[ "$1" == "--help" ]] || [[ "$1" == "-h" ]]; then
    if [[ $# -lt 1 ]]; then
        print_error "CONFIG_FILE is required"
    fi
    show_usage
    exit 0
fi

CONFIG_FILE="$1"
DBT_COMMAND="${2:-dbt run}"

print_info "=== REDSHIFT DBT EXECUTION VIA BASTION ==="
print_info "dbt Command: $DBT_COMMAND"
print_info "Config File: $CONFIG_FILE"

# Function to read config value with jq fallback
read_config_value() {
    local key="$1"
    local default_value="$2"
    local config_file="$3"
    
    if [[ -f "$config_file" ]] && command -v jq >/dev/null 2>&1; then
        local value=$(jq -r "$key // \"$default_value\"" "$config_file" 2>/dev/null)
        # Handle environment variable substitution
        if [[ "$value" =~ ^\$\{(.+)\}$ ]]; then
            local env_var="${BASH_REMATCH[1]}"
            value="${!env_var:-$default_value}"
        fi
        echo "$value"
    else
        echo "$default_value"
    fi
}

# Function to detect dbt operation type from SQL file path
detect_dbt_operation() {
    local sql_file="$1"
    
    # Extract operation from path pattern: sql/redshift/dbt/{operation}
    if [[ "$sql_file" =~ sql/redshift/dbt/([^/]+)\.sql$ ]]; then
        local operation="${BASH_REMATCH[1]}"
        echo "$operation"
    else
        # Default operation if pattern doesn't match
        echo "view"  # Default to view operation for dbt
    fi
}

# Function to get dbt operation-specific database
get_dbt_database() {
    local operation="$1"
    local config_file="$2"
    
    # dbt operations now use regular Redshift database with cross-database reference
    case "$operation" in
        "simple-all-users-view"|"verify-all-users-view"|"view"|"verification")
            # Use regular Redshift database (dev) for View creation, with cross-database reference to Zero-ETL
            echo "dev"
            ;;
        *)
            # Fallback to regular Redshift database
            echo "dev"
            ;;
    esac
}

# Function to load Redshift connection from bastion connection file
load_redshift_connection() {
    local connection_file="bastion-redshift-connection.json"
    
    print_info "Loading Redshift connection information..."
    
    # Check if connection file exists
    if [[ ! -f "$connection_file" ]]; then
        print_error "Connection file not found: $connection_file"
        print_error "Please run configure-bastion-redshift-sg.py first to generate connection information"
        exit 1
    fi
    
    # Validate jq is available
    if ! command -v jq >/dev/null 2>&1; then
        print_error "jq is required to parse connection information"
        exit 1
    fi
    
    # Extract connection information
    local host=$(jq -r '.connection.host // empty' "$connection_file" 2>/dev/null)
    local port=$(jq -r '.connection.port // 5439' "$connection_file" 2>/dev/null)
    local user=$(jq -r '.connection.username // "admin"' "$connection_file" 2>/dev/null)
    local password=$(jq -r '.connection.password // empty' "$connection_file" 2>/dev/null)
    local secret_name=$(jq -r '.connection.secret_name // empty' "$connection_file" 2>/dev/null)
    
    # Validate required connection parameters
    if [[ -z "$host" ]] || [[ "$host" == "null" ]]; then
        print_error "Redshift host not found in connection file"
        exit 1
    fi
    
    if [[ -z "$password" ]] || [[ "$password" == "null" ]]; then
        print_warning "Redshift password not found in connection file"
        print_info "Secret name: $secret_name"
    fi
    
    # Set connection variables (allow environment variable override)
    export REDSHIFT_HOST="${REDSHIFT_HOST:-$host}"
    export REDSHIFT_PORT="${REDSHIFT_PORT:-$port}"
    export REDSHIFT_USER="${REDSHIFT_USER:-$user}"
    export REDSHIFT_PASSWORD="${REDSHIFT_PASSWORD:-$password}"
    
    print_success "Redshift connection loaded:"
    print_info "  Host: $REDSHIFT_HOST"
    print_info "  Port: $REDSHIFT_PORT"
    print_info "  User: $REDSHIFT_USER"
    print_info "  Password: ${REDSHIFT_PASSWORD:+***set***}"
    
    return 0
}

# Load Redshift connection information
load_redshift_connection

# Set default database for dbt operations
REDSHIFT_DB="${REDSHIFT_DATABASE:-dev}"
print_info "Using dbt database: $REDSHIFT_DB"

print_info "Redshift Connection Configuration:"
print_info "  Host: $REDSHIFT_HOST"  
print_info "  Port: $REDSHIFT_PORT"
print_info "  Database: $REDSHIFT_DB"
print_info "  User: $REDSHIFT_USER"
print_info "  Password: ${REDSHIFT_PASSWORD:+***set***}"

# Validate required connection parameters
if [[ -z "$REDSHIFT_HOST" ]] || [[ "$REDSHIFT_HOST" == "null" ]]; then
    print_error "Redshift host is required. Check bastion-redshift-connection.json"
    exit 1
fi

if [[ -z "$REDSHIFT_PASSWORD" ]] || [[ "$REDSHIFT_PASSWORD" == "null" ]]; then
    print_warning "Redshift password not set. Database connection may fail."
fi

# Activate dbt virtual environment if it exists
if [[ -f "/tmp/dbt-venv/bin/activate" ]]; then
    print_info "Activating dbt virtual environment..."
    source /tmp/dbt-venv/bin/activate
fi

# Check if dbt is available
if ! command -v dbt >/dev/null 2>&1; then
    print_error "dbt command not found. Please run --step0 to install dbt first."
    exit 1
fi

# Function to create dbt profiles.yml
create_dbt_profiles() {
    # Set HOME directory explicitly if not set
    export HOME="${HOME:-/root}"
    local profiles_dir="$HOME/.dbt"
    local profiles_file="$profiles_dir/profiles.yml"
    
    print_info "Creating dbt profiles configuration..."
    print_info "Using HOME directory: $HOME"
    print_info "Profiles file location: $profiles_file"
    
    # Create .dbt directory if it doesn't exist
    mkdir -p "$profiles_dir"
    
    # Create profiles.yml with Zero-ETL integration support and proper types
    cat > "$profiles_file" << EOF
multitenant_analytics:
  outputs:
    dev:
      type: redshift
      host: $REDSHIFT_HOST
      user: $REDSHIFT_USER
      password: $REDSHIFT_PASSWORD
      port: 5439
      dbname: $REDSHIFT_DB
      schema: analytics
      threads: 1
      keepalives_idle: 0
      
  target: dev
EOF
    
    print_success "dbt profiles created: $profiles_file"
    return 0
}

# Function to setup dbt project
setup_dbt_project() {
    local dbt_project_dir="/tmp/dbt_project"
    local workspace_dir="/tmp/workspace"
    
    print_info "Setting up dbt project directory..."
    
    # Create dbt project directory
    mkdir -p "$dbt_project_dir"
    
    # Copy existing dbt files from workspace sql/redshift/dbt directory
    if [[ -d "$workspace_dir/sql/redshift/dbt" ]]; then
        print_info "Copying dbt project from workspace sql/redshift/dbt directory..."
        
        # Debug: Show what files exist in source directory
        print_info "Source directory contents:"
        ls -la "$workspace_dir/sql/redshift/dbt/"
        
        cp -r "$workspace_dir/sql/redshift/dbt"/* "$dbt_project_dir/" 2>/dev/null || true
        
        # Debug: Show what files were copied to destination
        print_info "Destination directory contents after copy:"
        ls -la "$dbt_project_dir/"
        
        # Also copy the main dbt directory macros if they exist in workspace
        if [[ -d "$workspace_dir/dbt/macros" ]]; then
            print_info "Copying dbt macros from workspace..."
            mkdir -p "$dbt_project_dir/macros"
            cp -r "$workspace_dir/dbt/macros"/* "$dbt_project_dir/macros/" 2>/dev/null || true
        fi
        
        # Verify that dbt_project.yml exists
        if [[ ! -f "$dbt_project_dir/dbt_project.yml" ]]; then
            print_error "dbt_project.yml not found after copying from workspace"
            print_error "Expected location: $dbt_project_dir/dbt_project.yml"
            return 1
        fi
        
        print_success "dbt project files copied successfully from workspace"
        print_info "dbt_project.yml confirmed at: $dbt_project_dir/dbt_project.yml"
    else
        print_error "sql/redshift/dbt directory not found in workspace: $workspace_dir"
        print_info "Workspace directory contents:"
        ls -la "$workspace_dir/" 2>/dev/null || echo "Workspace directory does not exist"
        return 1
    fi
    
    # Change to dbt project directory
    cd "$dbt_project_dir"
    
    print_success "dbt project setup completed: $dbt_project_dir"
    echo "$dbt_project_dir"
}

# Function to execute dbt command
execute_dbt_command() {
    local dbt_cmd="$1"
    
    print_info "Executing dbt command: $dbt_cmd"
    
    # Activate dbt virtual environment if it exists
    if [[ -f "/tmp/dbt-venv/bin/activate" ]]; then
        print_info "Activating dbt virtual environment..."
        source /tmp/dbt-venv/bin/activate
    fi
    
    # Create dbt profiles
    create_dbt_profiles
    
    # Setup dbt project
    setup_dbt_project
    if [[ $? -ne 0 ]]; then
        print_error "Failed to setup dbt project"
        return 1
    fi
    
    # Change to dbt project directory
    local project_dir="/tmp/dbt_project"
    if [[ ! -d "$project_dir" ]]; then
        print_error "dbt project directory not found: $project_dir"
        return 1
    fi
    
    cd "$project_dir"
    print_info "Working in dbt project directory: $(pwd)"
    
    # Verify dbt_project.yml exists
    if [[ ! -f "dbt_project.yml" ]]; then
        print_error "dbt_project.yml not found in $(pwd)"
        ls -la
        return 1
    fi
    
    # Execute dbt command
    if eval "$dbt_cmd"; then
        print_success "dbt command executed successfully"
        return 0
    else
        local exit_code=$?
        print_error "dbt command failed with exit code: $exit_code"
        return $exit_code
    fi
}

# Function to test dbt connection
test_dbt_connection() {
    print_info "Testing dbt connection to Redshift..."
    
    # Activate dbt virtual environment if it exists
    if [[ -f "/tmp/dbt-venv/bin/activate" ]]; then
        source /tmp/dbt-venv/bin/activate
    fi
    
    # Create dbt profiles
    create_dbt_profiles
    
    # Setup dbt project
    setup_dbt_project
    if [[ $? -ne 0 ]]; then
        print_error "Failed to setup dbt project"
        return 1
    fi
    
    # Change to dbt project directory
    local project_dir="/tmp/dbt_project"
    if [[ ! -d "$project_dir" ]]; then
        print_error "dbt project directory not found: $project_dir"  
        return 1
    fi
    
    cd "$project_dir"
    
    # Test dbt connection
    if dbt debug; then
        print_success "dbt connection test successful"
        return 0
    else
        print_error "dbt connection test failed"
        return 1
    fi
}

# Execute dbt command
print_info "=== STARTING REDSHIFT DBT EXECUTION ==="

# Record start time
start_time=$(date +%s)

# Test dbt connection first
if ! test_dbt_connection; then
    print_warning "dbt connection test failed, but continuing with execution..."
fi

# Execute dbt command
if execute_dbt_command "$DBT_COMMAND"; then
    # Calculate execution time
    end_time=$(date +%s)
    duration=$((end_time - start_time))
    
    print_success "=== REDSHIFT DBT EXECUTION COMPLETED SUCCESSFULLY ==="
    print_info "Execution time: ${duration}s"
    print_info "dbt Command: $DBT_COMMAND"
    print_info "Database: $REDSHIFT_DB"
    exit 0
else
    # Calculate execution time
    end_time=$(date +%s)
    duration=$((end_time - start_time))
    
    print_error "=== REDSHIFT DBT EXECUTION FAILED ==="
    print_info "Execution time: ${duration}s"
    print_info "dbt Command: $DBT_COMMAND"
    print_info "Database: $REDSHIFT_DB"
    exit 1
fi
