model_list:
  - model_name: bedrock-converse-us-claude-3-7-sonnet-v1
    litellm_params:
      model: bedrock/converse/us.anthropic.claude-3-7-sonnet-20250219-v1:0
      aws_access_key_id: os.environ/AWS_ACCESS_KEY_ID
      aws_secret_access_key: os.environ/AWS_SECRET_ACCESS_KEY
      aws_region_name: os.environ/AWS_REGION_NAME
      thinking: {"type": "enabled", "budget_tokens": 1024}
  
  - model_name: bedrock-converse-us-claude-3-5-sonnet-v2
    litellm_params:
      model: bedrock/converse/us.anthropic.claude-3-5-sonnet-20241022-v2:0
      aws_access_key_id: os.environ/AWS_ACCESS_KEY_ID
      aws_secret_access_key: os.environ/AWS_SECRET_ACCESS_KEY
      aws_region_name: os.environ/AWS_REGION_NAME
  
  - model_name: bedrock-converse-apac-claude-3-5-sonnet-v2
    litellm_params:
      model: bedrock/converse/apac.anthropic.claude-3-5-sonnet-20241022-v2:0
      aws_access_key_id: os.environ/AWS_ACCESS_KEY_ID
      aws_secret_access_key: os.environ/AWS_SECRET_ACCESS_KEY
      aws_region_name: os.environ/AWS_REGION_NAME
  
litellm_settings:
  fallbacks: [{"bedrock-converse-us-claude-3-7-sonnet-v1": ["bedrock-converse-us-claude-3-5-sonnet-v2", "bedrock-converse-apac-claude-3-5-sonnet-v2"]}]
  num_retries: 2
  request_timeout: 30
  aws_access_key_id: os.environ/AWS_ACCESS_KEY_ID
  aws_secret_access_key: os.environ/AWS_SECRET_ACCESS_KEY
  aws_region_name: us-east-1
  drop_params: true # サポート外のパラメータを無視する

general_settings:
  log_level: debug
  openai_api_base: "/v1"
  disable_user_auth: true  # 開発中は認証を無効化（本番環境では使用しないでください）

router_settings:
  default_model: bedrock-converse-us-claude-3-7-sonnet-v1
  failover: true
  timeout: 30
  retries: 3

openapi:
  openapi_version: "3.1.0"
  title: "LiteLLM API"
  description: "LiteLLM API for multiple LLM models"
  servers:
    - url: "/"
  info:
    version: "1.0.0"